src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 99999999, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: "datetime_immutable", nullable: true, options: ["default" => "CURRENT_TIMESTAMP", "comment" => "__hidden__"])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: "datetime_immutable", nullable: true, columnDefinition: "DATETIME on update CURRENT_TIMESTAMP")]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    private $user = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user_id)
    {
        $this->user = $user_id;
    }

    #[ORM\PrePersist]
    public function prePersist(): void
    {
        $this->created_at = new \DateTimeImmutable();
        dd($this->created_at);
    }

    #[ORM\PreUpdate]
    public function preUpdate(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('description', TextareaType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/post')]
class PostController extends AbstractController
{
    #[Route('/', name: 'app_post_index', methods: ['GET'])]
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_post_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PostRepository $postRepository): Response
    {

        $post = new Post();

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $postRepository->save($post, true);

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_show', methods: ['GET'])]
    public function show(Post $post): Response
    {
        return $this->render('post/show.html.twig', [
            'post' => $post,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_post_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Post $post, PostRepository $postRepository): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postRepository->save($post, true);

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, PostRepository $postRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->request->get('_token'))) {
            $postRepository->remove($post, true);
        }

        return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('app_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
{% for field in form %}
    {{ form_widget(field) }}
{% endfor %}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
<a class="btn btn-primary" href="{{ path('app_post_index') }}">Back to list</a>
{{ include('post/_delete_form.html.twig') }}
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts{% endblock %}

{% block body %}
    <div class="d-flex align-items-center justify-content-center">
        {% if app.request.attributes.get('_route') == 'app_post_index' %}
            <h1 class="text-center p-3">Posts</h1>
        {% endif %}
        {% if app.request.attributes.get('_route') == 'app_post_admin_index' %}
            <div class="justify-content-end">
                <a class="btn btn-primary" href="{{ path('app_post_new') }}">Create new</a>
            </div>
        {% endif %}
    </div>
    <div class="d-grid gap-5">
        {% for post in posts %}
            {{ include('post/post.html.twig') }}
        {% else %}
            <div>No records found</div>
        {% endfor %}
    </div>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Create new Post</h1>

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('app_post_index') }}">back to list</a>
{% endblock %}

templates/post/post.html.twig
<div class="card">
    <div class="card-body">
        <a class="text-decoration-none font-weight-bold font-size-lg h2-font-size"
           href="{{ 'app_blog' in app.request.attributes.get('_route')?path('app_blog_show', {'id': post.id}):path('app_post_show', {'id': post.id}) }}">
            <h2 class="fs-2 text-center">{{ post.title }}</h2>
        </a>
        <div class="d-flex align-items-center  p-3">
            <div class="col">
                {% if post.createdAt %}
                    <span class="badge bg-secondary">created {{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</span>
                {% endif %}
                {% if post.updatedAt %}
                    <span class="badge bg-info">updated {{ post.updatedAt ? post.updatedAt|date('Y-m-d H:i:s') : '' }}</span>
                {% endif %}
            </div>
            <div class="d-flex gap-3">
                {% if 'app_post' in app.request.attributes.get('_route') %}
                    <a class="btn btn-warning" href="{{ path('app_post_edit', {'id': post.id}) }}">Edit</a>
                    {{ include('post/_delete_form.html.twig') }}
                {% endif %}
            </div>
        </div>
        <div class="description text-center">{{ post.description |raw }}</div>
    </div>
</div>

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
    {{ include('post/post.html.twig') }}
{% endblock %}